DELETE FROM PARAMETER_VALUE;
DELETE FROM PARAMETER;
DELETE FROM PARAMETER;
DELETE FROM PRODUCTION_RULE;
DELETE FROM MOLD;
DELETE FROM PAN;
DELETE FROM DISTRIBUTOR;
DELETE FROM FORMAT;
DELETE FROM AREA;

INSERT INTO AREA VALUES(0, 'Mold');
INSERT INTO AREA VALUES(1, 'Pan');
INSERT INTO AREA VALUES(2, 'Distributor');

INSERT INTO SUB_AREA VALUES(0, 0, 'Upper Mold');
INSERT INTO SUB_AREA VALUES(1, 0, 'Mid Mold');
INSERT INTO SUB_AREA VALUES(2, 0, 'Lower Mold');

INSERT INTO SUB_AREA VALUES(3, 1, 'Upper Pan');
INSERT INTO SUB_AREA VALUES(4, 1, 'Mid Pan');
INSERT INTO SUB_AREA VALUES(5, 1, 'Lower Pan');

INSERT INTO SUB_AREA VALUES(6, 1, 'Upper Distributor');
INSERT INTO SUB_AREA VALUES(7, 1, 'Mid Distributor');
INSERT INTO SUB_AREA VALUES(8, 1, 'Lower Distributor');

INSERT INTO PRODUCTION_RULE_GROUP VALUES(0, 'Foil');
INSERT INTO PRODUCTION_RULE_GROUP VALUES(1, 'Corrosion Resistant');
INSERT INTO PRODUCTION_RULE_GROUP VALUES(2, 'LD Steel');


INSERT INTO PRODUCTION_RULE VALUES(0, 2, 'Stainless Steel');
INSERT INTO PRODUCTION_RULE VALUES(0, 1, '')
INSERT INTO PARAMETER VALUES


INSERT INTO FORMAT VALUES(0, .05, .20, 10);
INSERT INTO FORMAT VALUES(1, .04, .20, 14);
INSERT INTO FORMAT VALUES(2, .20, .20, 5);

INSERT INTO DISTRIBUTOR VALUES(0, 100, 200);
INSERT INTO DISTRIBUTOR VALUES(1, 250, 152);
INSERT INTO DISTRIBUTOR VALUES(2, 50, 145);

INSERT INTO MOLD VALUES(0, 35, 234, 1);
INSERT INTO MOLD VALUES(1, 40, 183, 2);
INSERT INTO MOLD VALUES(2, 30, 23, 0);

INSERT INTO PAN VALUES(0, 40, 233);
INSERT INTO PAN VALUES(1, 60, 63);
INSERT INTO PAN VALUES(2, 20, 147);



/*
SELECT 
(SELECT PARAMETER_NAME FROM PARAMETER WHERE r.METADATA_AIM = PARAMETER_ID) AS NAME,
(SELECT NVL(TEXT, TO_CHAR(DIGIT)) FROM PARAMETER_VALUE WHERE r.METADATA_MIN = PARAMETER_ID) AS MIN, 
(SELECT NVL(TEXT, TO_CHAR(DIGIT)) FROM PARAMETER_VALUE WHERE r.METADATA_AIM = PARAMETER_ID) AS AIM,
(SELECT NVL(TEXT, TO_CHAR(DIGIT)) FROM PARAMETER_VALUE WHERE r.METADATA_MAX = PARAMETER_ID) AS MAX,
(SELECT UNIT FROM PARAMETER WHERE r.METADATA_AIM = PARAMETER_ID) AS UNIT 
FROM METADATA r where r.production_rule_id = 0;
*/

Select * from Production_Rule;

--SELECT * FROM METADATA R JOIN PARAMETER P ON R.PARAMETER_ID = P.PARAMETER_ID;