
DROP TABLE PARAMETER CASCADE CONSTRAINTS;
DROP TABLE PARAMETER_VALUE CASCADE CONSTRAINTS;
DROP TABLE PRODUCTION_RULE_GROUP CASCADE CONSTRAINTS;
DROP TABLE PRODUCTION_RULE CASCADE CONSTRAINTS;
DROP TABLE METADATA CASCADE CONSTRAINTS;



CREATE TABLE PARAMETER(
PARAMETER_ID NUMBER NOT NULL,
PARAMETER_NAME VARCHAR2(50),
DEFAULT_VALUE NUMBER,
UPPER_LIMIT NUMBER,
LOWER_LIMIT NUMBER,
MEASUREMENT_TIME VARCHAR2(50),
UNIT VARCHAR2(50),
ORIGIN VARCHAR2(50),
ENTRY_TYPE VARCHAR2(50),
IS_TEXT NUMBER(1),
IS_ACTIVE NUMBER(1),
SUB_AREA VARCHAR2(50),
PROCESS_PARAMETER NUMBER(1),
QUALITY_PARAMETER NUMBER(1)
);


CREATE TABLE PARAMETER_VALUE(
PARAMETER_ID NUMBER,
TEXT VARCHAR2(50),
DIGIT NUMBER
);

CREATE TABLE PRODUCTION_RULE(
PRODUCTION_RULE_ID NUMBER,
PRODUCTION_RULE_GROUP_ID NUMBER,
PRODUCTION_RULE_NAME VARCHAR2(50)
);

CREATE TABLE METADATA(
PRODUCTION_RULE_ID NUMBER,
METADATA_AIM NUMBER,
METADATA_MIN NUMBER,
METADATA_MAX NUMBER
);

CREATE TABLE PRODUCTION_RULE_GROUP(
PRODUCTION_RULE_GROUP_ID NUMBER,
PRODUCTION_RULE_GROUP_NAME VARCHAR2(50)
);

ALTER TABLE PARAMETER
ADD CONSTRAINT PK_PARAMETER PRIMARY KEY (PARAMETER_ID) ENABLE;

ALTER TABLE PARAMETER_VALUE
ADD CONSTRAINT PK_PARAMETER_VALUE PRIMARY KEY (PARAMETER_ID) ENABLE
ADD CONSTRAINT FK_PARAMETER_VALUE FOREIGN KEY (PARAMETER_ID) REFERENCES PARAMETER(PARAMETER_ID) ENABLE;

ALTER TABLE PRODUCTION_RULE
ADD CONSTRAINT PK_PRODUCTION_RULE_ID PRIMARY KEY (PRODUCTION_RULE_ID) ENABLE
ADD CONSTRAINT FK_PRODUCTION_RULE_GROUP FOREIGN KEY (PRODUCTION_RULE_GROUP_ID) REFERENCES PRODUCTION_RULE_GROUP(PRODUCTION_RULE_GROUP_ID);

ALTER TABLE PRODUCTION_RULE_GROUP
ADD CONSTRAINT PK_PRODUCTION_RULE_GROUP PRIMARY KEY (PRODUCTION_RULE_GROUP_ID) ENABLE;

ALTER TABLE METADATA
ADD CONSTRAINT FK_PRODUCTION_RULE FOREIGN KEY (PRODUCTION_RULE_ID) REFERENCES PRODUCTION_RULE(PRODUCTION_RULE_ID) ENABLE
ADD CONSTRAINT FK_AIM FOREIGN KEY (METADATA_AIM) REFERENCES PARAMETER(PARAMETER_ID) ON DELETE CASCADE
ADD CONSTRAINT FK_MIN FOREIGN KEY (METADATA_MIN) REFERENCES PARAMETER(PARAMETER_ID) ON DELETE CASCADE
ADD CONSTRAINT FK_MAX FOREIGN KEY (METADATA_MAX) REFERENCES PARAMETER(PARAMETER_ID) ON DELETE CASCADE;




